version: '3.8'

x-common-spec:
  &common-spec
  env_file: ./config/.env

x-django-container-spec:
  &django-container-spec
  <<: *common-spec
  build:
    context: .
    dockerfile: Dockerfile-django
    args:
      DJANGO_ENV: development
      DPT_VENV_CACHING: $DPT_VENV_CACHING
    cache_from:
      - "{{ cookiecutter.project_slug }}:dev"
      - "{{ cookiecutter.project_slug }}:latest"
      - "*"
  volumes:
    - &py-code-volume ".:/code"
    - django-static:/var/www/django/static
  depends_on:
    - postgres
    - rabbitmq
    - mailhog
  environment:
    PYTHONUNBUFFERED: "0"

x-celery-environment:
  &celery-environment
  environment:
    PYTHONUNBUFFERED: "0"
    SKIP_INSTALL: "1"

services:
  django:
    <<: *django-container-spec
    image: "{{ cookiecutter.project_slug }}:dev"
    ports:
      - "8000:8000"
    volumes:
      - *py-code-volume
    command: python manage.py runserver 0.0.0.0:8000
    entrypoint: /usr/bin/wait-for-it.sh postgres:5432 -t 60 -- entrypoint.sh --

  postgres:
    <<: *common-spec
    image: postgres:14.1
    restart: unless-stopped
    volumes:
      - ".data/postgres:/var/lib/postgresql/data"
      - ".data/db-mirror:/db-mirror" # Used by ansible mirror playbook
      - "./scripts/create-citext-extension.sql:/docker-entrypoint-initdb.d/create-citext-extension.sql"
    # Comment in the following lines to connect to your Dockerized instance of Postgres from your host machine.
    # Change the host port (before colon) if you have a local instance of Postgres running on that port.
    ports:
      - "5432:5432"
    environment:
      # credentials taken from .env file
      POSTGRES_USER: "${DJANGO_DATABASE_USER:-{{ cookiecutter.project_slug }}}"
      POSTGRES_PASSWORD: "${DJANGO_DATABASE_PASSWORD:-{{ cookiecutter.project_slug }}}"

  rabbitmq:
    <<: *common-spec
    image: rabbitmq:3.7.2-management-alpine
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_ERLANG_COOKIE=JKSDFHSJF7834GHBF3FBEI
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq
      - RABBITMQ_DEFAULT_VHOST=my_vhost

  mailhog:
    <<: *common-spec
    image: mailhog/mailhog:v1.0.0
    container_name: temp_proj_mailhog
    ports:
      - "8025:8025"
    logging:
      driver: "none"
